### ISSUE TITLE
How does the compute shader avoid race conditions?

### ISSUE THREAD

**Issue by shayded-exe** [GarrettGunnell/Cellular-Automata#1]
I see that the compute shader is reading from and writing to the same texture.

Doesn't this result in an undefined order of execution? Where the results of the current generation affect itself while it's being computed?

Everything I can find online indicates that you would normally use two buffers and swap between them.

I'm new to compute shaders so I'm curious to hear your reasoning. Love the videos!

**Comment by trungpro200** [comment]
uh..

**Comment by GarrettGunnell** [comment]
it doesnt, I made this when I was a worse graphics programmer (thumbs up emoji)

it worked on my machine tho

**Comment by shayded-exe** [comment]
Gotcha, thanks for answering. I wanted to make sure there wasn't some magic thing I was missing!
